
description: AI-powered anti-distraction and focus mastery app
version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.2.0
  stacked_services: ^0.9.7
  firebase_core: ^3.20.0
  firebase_auth: ^4.4.0
  cloud_firestore: ^4.5.0
  google_sign_in: ^6.0.3
  sign_in_with_apple: ^3.4.0
  provider: ^6.0.5
  flutter_slidable: ^3.0.0
  just_audio: ^0.9.31
  audio_session: ^0.1.7
  flutter_spinkit: ^5.1.0
  percent_indicator: ^4.2.2
  flutter_hooks: ^0.18.5
  get_it: ^7.2.0
  intl: ^0.18.0
  shared_preferences: ^2.1.1
  hive: ^2.2.3
  hive_flutter: ^1.2.0
  flutter_local_notifications: ^14.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.11.0
  build_runner: ^2.4.0
  stacked_generator: ^0.6.4
